<?php
$article = [
  ['aria_label'   => 'article 1',
  'topic'         => 'none',
  'header'        => 'Выделение CSS-настроек в отдельный репозиторий',
  'alt_header'    => 'Project-Euler-CSS',
  'preview'       => 'Project-Euler-CSS - это CSS-настройки для моего блога Project-Euler-Blog.
  Выделение CSS-настроек в отдельный репозиторий позволяет
  использовать их повторно в разных проектах и избавляет от необходимости
  вносить одни и те же изменения в каждый проект...',
  'link'          => '<a href="vydelenie-css-v-otdelnyj-repozitorij.php"><b>читать</b></a>',
  ],
  ['aria_label'   => 'article 2',
  'topic'         => 'none',
  'header'        => 'Установка XAMPP на сервер',
  'alt_header'    => 'Установка XAMPP на сервер',
  'preview'       => 'Краткий гайд...',
  'link'          => '<a href="ustanovka-xampp-na-server.php"><b>читать</b></a>',
  ],
  ['aria_label'   => 'article 3',
  'topic'         => 'none',
  'header'        => 'Простой сайт на HTML',
  'alt_header'    => 'Project-Euler-Blog',
  'preview'       => 'Чтобы сделать сайт доступным из любой точки мира, самым простым вариантом
  будет запустить его HTML-страницу на VPS-сервере с XAMPP.
  Весь процесс можно разбить на несколько простых шагов...',
  'link'          => '<a href="prostoj-sajt-na-html.php"><b>читать</b></a>',
  ],
  ['aria_label'   => 'article 4',
  'topic'         => 'none',
  'header'        => 'Установка SSL-сертификата на сайт',
  'alt_header'    => 'Установка SSL-сертификата на сайт',
  'preview'       => 'Браузеры помечают сайты без HTTPS как «небезопасные».
  Чтобы сайт работал через HTTPS небходимо установить SSL-сертификат...',
  'link'          => '<a href="ustanovka-ssl-sertifikata-na-sajt.php"><b>читать</b></a>',
  ],
  ['aria_label'   => 'article 5',
  'topic'         => 'problem',
  'header'        => 'Проект Эйлер 1 задача на PHP',
  'alt_header'    => 'Числа, кратные 3 или 5',
  'preview'       => 'Решая эту задачу, постарался не только отработать конструкции языка <b>PHP</b>,
  но и сделал небольшой <b>онлайн-калькулятор</b>, позволяющий проверить ваши вычисления...',
  'link'          => '<a href="project-euler-1-php.php"><b>читать</b></a>',
  ],
  ['aria_label'   => 'article 6',
  'topic'         => 'none',
  'header'        => 'Project-Euler Open Source',
  'alt_header'    => 'Project-Euler Open Source',
  'preview'       => '<b>Project-Euler</b> - это опенсорс проект, который помогает изучить
  и попрактиковать конструкции различных языков программирования...',
  'link'          => '<a href="project-euler-open-source.php"><b>читать</b></a>',
  ],
  ['aria_label'   => 'article 7',
  'topic'         => 'problem',
  'header'        => 'Проект Эйлер 2 задача на PHP',
  'alt_header'    => 'Четные числа Фибоначчи',
  'preview'       => 'Реализация задачи на PHP с онлайн-калькулятором для проверки вычислений"...',
  'link'          => '<a href="project-euler-2-php.php"><b>читать</b></a>',
  ],
];
